language: python
python: 2.7
install:
  - mkdir -p buildout-cache/eggs
  - mkdir -p buildout-cache/downloads
  - pip install -U setuptools==0.6c11
  - pip uninstall -y distribute
  - python bootstrap.py -c travis.cfg
  - bin/buildout -N -t 3 -c travis.cfg
script:
  - bin/test
  - bin/code-analysis
after_success:
  - bin/createcoverage run bin/test
  - pip install -q coveralls
  - coveralls
after_failure:
  - bin/buildout annotate -c travis.cfg
